Feat/typescript auth
TorinAsakura/alexgrupp25.github.io pull request #4
Opened 2023-05-21 13:38 UTC by alexgrupp25

Add auth function 
- downgraded versions:  
  - eslint to 8.18 
  - @types/eslint to 8

2023-05-21 13:51 UTC, alexgrupp25 commented
Мне тут кнопочка Merge pull request доступна. У меня лишние права есть? или её необходимо прожать?)

2023-05-21 13:53 UTC, TorinAsakura commented
@alexgrupp25 Почитай для чего нужны пры и не тыкай куда не просят

2023-05-22 17:30 UTC, TorinAsakura requested changes

2023-05-22 17:30 UTC, TorinAsakura commented on auth/auth.ts
> +interface ILogged {
посмотри что написано в гайде тайпскрипта по поводу букву I

2023-05-22 17:30 UTC, TorinAsakura commented on auth/auth.ts
> +interface IUser {
хорошей практикой является вынос интерфейсов во внешний файл, это называется interfaces segregation, относится к SOLID

2023-05-22 17:30 UTC, TorinAsakura commented on auth/auth.ts
> +}
последняя строка…

2023-05-22 17:30 UTC, TorinAsakura commented on css/styles.css
> +body {
вообще, вёрстка не нужна была)

2023-05-22 17:30 UTC, TorinAsakura commented on js/auth.js
> +const registration = (userName, password) => {
зачем тут жс?

2023-05-23 17:56 UTC, TorinAsakura requested changes
## Общий обзор

Код в целом чистый и легко читаемый, но есть пара моментов, которые можно улучшить.

## handleError

`handleError` принимает функцию обратного вызова и выполняет её в блоке try/catch. Если происходит ошибка, она выводится в консоль. Вместо `console.log` лучше использовать `console.error` для большей ясности.

## registration, authorization

Всё ок, но можно было бы разбить эту функцию на более мелкие функции для улучшения читаемости.

## Общие замечания

В целом, код хорошо структурирован и легко читается. Но можно было бы использовать более декларативный подход и разбить функции на более мелкие для улучшения читаемости. Также, вместо `console.log` в функции `handleError` можно было бы использовать `console.error`. 

В функциях `whoAmI` и `logOut`проверка на наличие активного пользователя дублируется. Это можно было бы вынести в отдельную функцию, чтобы избежать повторения кода.

2023-05-24 20:13 UTC, alexgrupp25 commented
@TorinAsakura Разбил функции на более мелкие, вынес их в отдельные модули и экспортировал. Надеюсь я правильно понял, что так надо было сделать. Для моего восприятия апка стала сложнее. Возникла проблема с областью видимости userStatus - помоему решил костыльно. И после правки ошибок от yarn lint вознникла проблема, что у авторизованного пользователя его статус в true не хочет меняется. поэтому пока на ревью не кидаю, завтра поправлю уже совсем голова не варит. Лонгрид написал, вдруг ты бегло посмотришь и скажешь, что не туда думаю:)

2023-05-24 20:14 UTC, TorinAsakura commented
@alexgrupp25 Я не смотрю бегло, я проверяю тщательно каждый коммит. Доброй ночи.

2023-05-26 23:22 UTC, TorinAsakura requested changes
- последние строки
Проверь линтер

2023-05-26 23:22 UTC, TorinAsakura commented on auth/interfaces.ts
> +
зачем?

2023-05-27 18:24 UTC, alexgrupp25 commented on auth/interfaces.ts
> +
Пропустил комментарий, почему-то уведомление не пришло.  Я не понял о чём речь тут

2023-05-27 21:09 UTC, TorinAsakura commented on auth/interfaces.ts
> +
Зачем пустая строка?

2023-05-27 21:27 UTC, TorinAsakura requested changes
должно быть единообразное написание - где-то у тебя camelCase, где-то PascalCase
файлы именуются через camelCase и kebab-case, но никак не через PascalCase

2023-05-27 22:20 UTC, TorinAsakura approved these changes

2023-05-27 22:20 UTC, merged